SHELL=/bin/bash

COVERAGE_RES=walltime=02:00:00,nodes=1:ppn=1,mem=10gb

COVERAGE_MSU_RES=walltime=00:10:00,nodes=1:ppn=1,mem=10gb

BLAT_RES=walltime=60:00:00,nodes=1:ppn=1,mem=3gb

GALGAL5_SOURCES=inputs/galGal5/Chicken_Chr1_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr2_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr3_PBJelly_14.1.15.QUIVER.fasta \
  inputs/galGal5/Chicken_Chr4_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr5_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr6_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr7_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr8_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr9_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr10_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr11_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr12_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr13_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr14_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr15_PBjelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr16_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr17_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr18_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr19_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr20_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr21_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr22_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr23_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr24_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr25_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr26_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr27_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr28_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_Chr32_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_ChrW_PBJelly_14.1.15_QUIVER.fasta \
  inputs/galGal5/Chicken_ChrZ_PBJelly_14.1.15_QUIVER.fasta

MOLECULO_READS=outputs/moleculo/LR6000017-DNA_A01-LRAAA-1_LongRead_500_1499nt.fastq \
  outputs/moleculo/LR6000017-DNA_A01-LRAAA-1_LongRead.fastq \
  outputs/moleculo/LR6000017-DNA_A01-LRAAA-2_LongRead_500_1499nt.fastq \
  outputs/moleculo/LR6000017-DNA_A01-LRAAA-2_LongRead.fastq \
  outputs/moleculo/LR6000017-DNA_A01-LRAAA-3_LongRead_500_1499nt.fastq \
  outputs/moleculo/LR6000017-DNA_A01-LRAAA-3_LongRead.fastq \
  outputs/moleculo/LR6000017-DNA_A01-LRAAA-4_LongRead_500_1499nt.fastq \
  outputs/moleculo/LR6000017-DNA_A01-LRAAA-4_LongRead.fastq \
  outputs/moleculo/LR6000017-DNA_A01-LRAAA-5_LongRead_500_1499nt.fastq \
  outputs/moleculo/LR6000017-DNA_A01-LRAAA-5_LongRead.fastq
