#!/bin/bash -login

mkdir -p /mnt/scratch/tg/irberlui/biodata/galGal/workdir/output/
mkdir -p /mnt/scratch/tg/irberlui/biodata/galGal/workdir/results/

write_submit_script() {
  local RUN_ID="$1"
  local INPUT="$2"
  local DATABASE="$3"
  local OUTPUT="$4"
  local PROGRAM="$5"
  local HOURS="$6"

  cat <<EOT1> /mnt/scratch/tg/irberlui/biodata/galGal/workdir/submit.blast.${RUN_ID}
#!/bin/bash -login
#PBS -l walltime=${HOURS}:00:00,nodes=1:ppn=8
#PBS -l mem=400mb
#PBS -j oe
#PBS -o /mnt/scratch/tg/irberlui/biodata/galGal/workdir/output/output.blast.${RUN_ID}
#PBS -N ${RUN_ID}
#PBS -W umask=027
#PBS -A ged-intel11

set -exu

module load BLAST

cd \$PBS_O_WORKDIR

blastall -i $INPUT -d $DATABASE -e 1e-3 -p $PROGRAM -o $OUTPUT -a 8 -v 4 -b 4

cat \${PBS_NODEFILE}       # Output Contents of the PBS NODEFILE

env | grep PBS            # Print out values of the current jobs PBS environment variables

qstat -f \${PBS_JOBID}     # Print out final statistics about resource uses before job exits
EOT1

}

#write_submit_script chick.x.human ../outputs/rna/only_rna.fa.renamed.fasta ../outputs/human/human.protein.faa ../workdir/results/chick.x.human blastx 20
#qsub /mnt/scratch/tg/irberlui/biodata/galGal/workdir/submit.blast.chick.x.human

#write_submit_script human.x.chick ../outputs/human/human.protein.faa ../outputs/rna/only_rna.fa.renamed.fasta ../workdir/results/human.x.chick tblastn 20
#qsub /mnt/scratch/tg/irberlui/biodata/galGal/workdir/submit.blast.human.x.chick



#write_submit_script chick.x.uniprot ../outputs/rna/only_rna.fa.renamed.fasta ../outputs/uniprot/uniprot_sprot.fasta ../workdir/results/chick.x.uniprot blastx 20
#qsub /mnt/scratch/tg/irberlui/biodata/galGal/workdir/submit.blast.chick.x.uniprot

#write_submit_script uniprot.x.chick ../outputs/uniprot/uniprot_sprot.fasta ../outputs/rna/only_rna.fa.renamed.fasta ../workdir/results/uniprot.x.chick tblastn 20
#qsub /mnt/scratch/tg/irberlui/biodata/galGal/workdir/submit.blast.uniprot.x.chick



write_submit_script chick.x.uniprot ../outputs/chicken_transcripts/global_merged.fa.clean.nr.renamed.fasta ../outputs/uniprot/uniprot_sprot.fasta ../workdir/results/chick.x.uniprot blastx 96
qsub /mnt/scratch/tg/irberlui/biodata/galGal/workdir/submit.blast.chick.x.uniprot

write_submit_script uniprot.x.chick ../outputs/uniprot/uniprot_sprot.fasta ../outputs/chicken_transcripts/global_merged.fa.clean.nr.renamed.fasta  ../workdir/results/uniprot.x.chick tblastn 96
qsub /mnt/scratch/tg/irberlui/biodata/galGal/workdir/submit.blast.uniprot.x.chick
