#!/bin/bash -login

GALDIR=/mnt/scratch/tg/irberlui/biodata/galGal
WORKDIR=$GALDIR/workdir

mkdir -p $WORKDIR/output/

cat <<EOT1> $WORKDIR/submit.${1}
#!/bin/bash -login
#PBS -l walltime=01:00:00,nodes=1:ppn=1
#PBS -l mem=10gb
#PBS -j oe
#PBS -o $WORKDIR/output/output.${1}
#PBS -N bam_cov.${1}
#PBS -A ged-intel11
#PBS -W umask=027

set -exu

/mnt/home/irberlui/Envs/bioinfo/bin/bioinfo bam_coverage $GALDIR/inputs/galGal4/galGal4.fa.masked.gz $GALDIR/outputs/moleculo/LR6000017-DNA_A01-LRAAA-AllReads.sorted.bam ${1} $GALDIR/outputs/moleculo/LR6000017-DNA_A01-LRAAA-AllReads.fastq --mapq=30


cat \${PBS_NODEFILE}       # Output Contents of the PBS NODEFILE

env | grep PBS            # Print out values of the current jobs PBS environment variables

qstat -f \${PBS_JOBID}     # Print out final statistics about resource uses before job exits
EOT1

qsub $WORKDIR/submit.${1}
