#!/bin/bash -login

mkdir -p /mnt/scratch/tg/irberlui/biodata/galGal/workdir/output/
mkdir -p /mnt/scratch/tg/irberlui/biodata/galGal/workdir/results/

RUN_ID=chick.x.uniprot

cat <<EOT1> /mnt/scratch/tg/irberlui/biodata/galGal/workdir/submit.blast.${RUN_ID}
#!/bin/bash -login
#PBS -l walltime=20:00:00,nodes=1:ppn=8
#PBS -l mem=400mb
#PBS -j oe
#PBS -o /mnt/scratch/tg/irberlui/biodata/galGal/workdir/output/output.blast.${RUN_ID}
#PBS -N ${RUN_ID}
#PBS -A ged-intel11
#PBS -W umask=027

set -exu

module load BLAST

cd \$PBS_O_WORKDIR

blastall -i ../outputs/rna/only_rna.fa.renamed.fasta -d ../outputs/uniprot/uniprot_sprot.fasta -e 1e-3 -p blastx -o ../workdir/results/chick.x.uniprot -a 8 -v 4 -b 4

cat \${PBS_NODEFILE}       # Output Contents of the PBS NODEFILE

env | grep PBS            # Print out values of the current jobs PBS environment variables

qstat -f \${PBS_JOBID}     # Print out final statistics about resource uses before job exits
EOT1

qsub /mnt/scratch/tg/irberlui/biodata/galGal/workdir/submit.blast.${RUN_ID}
